name: Release

on:
  push:
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build
        run: | 
         sudo apt-get update 
         sudo apt-get install musl-tools musl musl-dev libssl-dev pkg-config g++
         sudo cp /usr/bin/g++ /usr/bin/musl-g++
         musl-g++ --version
         PKG_CONFIG_ALLOW_CROSS=1 cargo build --target x86_64-unknown-linux-musl --release
