name: Test

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: ubuntu_16_04-x86_64
            os: ubuntu-16.04
            TARGET_CPU: x86-64

          - name: ubuntu_18_04-x86_64
            os: ubuntu-18.04
            TARGET_CPU: x86-64

          - name: ubuntu_20_04-x86_64
            os: ubuntu-20.04
            TARGET_CPU: x86-64

          - name: osx_11_0-x86_64
            os: macos-11.0
            TARGET_CPU: x86-64

          - name: osx_10_11-x86_64
            os: macos-10.15
            TARGET_CPU: x86-64

          - name: win-x86_64
            os: windows-2019
            TARGET_CPU: x86-64

          - name: ubuntu_18_04-x86_64-haswell
            os: ubuntu-18.04
            TARGET_CPU: haswell

          - name: win-x86_64-haswell
            os: windows-2019
            TARGET_CPU: haswell

    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      ### BUILD CACHE ###
      # NB: We install gnu-tar because BSD tar is buggy on Github's macos machines. https://github.com/actions/cache/issues/403
      - name: Install GNU tar (Macos)
        if: ${{contains( matrix.os, 'macos' )}}
        run: |
          brew install gnu-tar
          echo PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH" >> $GITHUB_ENV
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{matrix.name}}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install nasm
        run: brew install nasm
        if: ${{contains( matrix.os, 'macos' )}}
      # - name: Install nasm
      #   run: choco install nasm
      #   if: ${{contains( matrix.os, 'windows' )}}
      - name: Install nasm
        run: |
            curl https://argoyal.s3.us-east-2.amazonaws.com/nasm-2.14.02-installer-x64.exe --output nasm.exe
            ./nasm.exe /S
        if: ${{contains( matrix.os, 'windows' )}}

      - name: Set Path
        run: |
            echo "C:\Program Files\nasm" >> $GITHUB_PATH
            echo "C:\Program Files (x86)\nasm" >> $GITHUB_PATH
        if: ${{contains( matrix.os, 'windows' )}}
        shell: bash

      - name: Test nasm Install
        run: nasm
        shell: bash
        if: ${{contains( matrix.os, 'windows' )}}
      - name: Install nasm
        run: sudo apt install nasm
        if: ${{contains( matrix.os, 'ubuntu' )}}
      - name: Install dssim
        run: cargo install dssim
      - name: Check Build
        run: cargo check --all
      - name: Test Build
        run: cargo test --all
        env:
          RUSTFLAGS: -C target-cpu=${{matrix.TARGET_CPU}}
      - name: Build Release
        run: cargo build --all
        shell: bash
        env:
          RUSTFLAGS: -C target-cpu=${{matrix.TARGET_CPU}}
